on:
  workflow_call:
    inputs:
      features:
        description: Non-default crate features to enable
        required: false
        type: string
      timeout-minutes:
        description: Minimum supported Rust version
        default: 20
        required: false
        type: number
    secrets:
      token:
        description: Codecov API token
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          default: true

      - name: Generate code coverage report
        uses: actions-rs/tarpaulin@v0.1.3
        with:
          version: '0.18.3'
          args: '-p isahc --run-types Tests,Doctests --features "${{ inputs.features }}"'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.token }}
          fail_ci_if_error: false
