on:
  workflow_call:
    inputs:
      features:
        description: Non-default crate features to test
        required: false
        type: string
      msrv:
        description: Minimum supported Rust version
        default: stable
        required: false
        type: string
      timeout-minutes:
        description: The maximum number of minutes to let the job run
        default: 20
        required: false
        type: number

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.msrv }}
          default: true

      - name: Run tests
        run: cargo test --features=${{ inputs.features }}

  lint:
    name: Run Clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features=${{ inputs.features }}
